#include "m16c_mem_map.h"

const cl_m16c_flash_block cl_m16c_mem_map::m_m16c_flash_blocks[] = {
	cl_m16c_flash_block("A", FLASH_BLOCK_A_NR, FLASH_BLOCK_A_BEGIN, FLASH_BLOCK_A_END, FLASH_BLOCK_A_SIZE),
	cl_m16c_flash_block("12", FLASH_BLOCK_12_NR, FLASH_BLOCK_12_BEGIN, FLASH_BLOCK_12_END, FLASH_BLOCK_12_SIZE),
	cl_m16c_flash_block("11", FLASH_BLOCK_11_NR, FLASH_BLOCK_11_BEGIN, FLASH_BLOCK_11_END, FLASH_BLOCK_11_SIZE),
	cl_m16c_flash_block("10", FLASH_BLOCK_10_NR, FLASH_BLOCK_10_BEGIN, FLASH_BLOCK_10_END, FLASH_BLOCK_10_SIZE),
	cl_m16c_flash_block("9", FLASH_BLOCK_9_NR, FLASH_BLOCK_9_BEGIN, FLASH_BLOCK_9_END, FLASH_BLOCK_9_SIZE),
	cl_m16c_flash_block("8", FLASH_BLOCK_8_NR, FLASH_BLOCK_8_BEGIN, FLASH_BLOCK_8_END, FLASH_BLOCK_8_SIZE),
	cl_m16c_flash_block("7", FLASH_BLOCK_7_NR, FLASH_BLOCK_7_BEGIN, FLASH_BLOCK_7_END, FLASH_BLOCK_7_SIZE),
	cl_m16c_flash_block("6", FLASH_BLOCK_6_NR, FLASH_BLOCK_6_BEGIN, FLASH_BLOCK_6_END, FLASH_BLOCK_6_SIZE),
	cl_m16c_flash_block("5", FLASH_BLOCK_5_NR, FLASH_BLOCK_5_BEGIN, FLASH_BLOCK_5_END, FLASH_BLOCK_5_SIZE),
	cl_m16c_flash_block("4", FLASH_BLOCK_4_NR, FLASH_BLOCK_4_BEGIN, FLASH_BLOCK_4_END, FLASH_BLOCK_4_SIZE),
	cl_m16c_flash_block("3", FLASH_BLOCK_3_NR, FLASH_BLOCK_3_BEGIN, FLASH_BLOCK_3_END, FLASH_BLOCK_3_SIZE),
	cl_m16c_flash_block("2", FLASH_BLOCK_2_NR, FLASH_BLOCK_2_BEGIN, FLASH_BLOCK_2_END, FLASH_BLOCK_2_SIZE),
	cl_m16c_flash_block("1", FLASH_BLOCK_1_NR, FLASH_BLOCK_1_BEGIN, FLASH_BLOCK_1_END, FLASH_BLOCK_1_SIZE),
	cl_m16c_flash_block("0", FLASH_BLOCK_0_NR, FLASH_BLOCK_0_BEGIN, FLASH_BLOCK_0_END, FLASH_BLOCK_0_SIZE)
};
